### ISSUE TITLE
User setttng for reverse sortiing doesn't work

### ISSUE THREAD

**Issue by dgutkowsky** [stpl/redmine_issue_history#3]
as in the subject

(Redmine 2.3.3)

**Comment by saily** [comment]
Ran into the same issue.

**Comment by saiballo** [comment]
open redmine_issue_history/app/views/issues/_history.html.erb and change this line:

<% for journal in journals.sort.reverse%>

to this

<% for journal in journals.sort %>

**Comment by saily** [comment]
i've opened a pull 8 month ago, please merge!

**Comment by saily** [comment]
See #4

**Comment by stpl** [comment]
Have merged PR https://github.com/stpl/redmine_issue_history/pull/4
